### PR TITLE
Fix sorting, add pull request links

### LINKED ISSUE #26: Progress page is sorted weirdly
Lots of high install plugins are quite far down:
i.e. workflow-job and a number of others
https://jenkins-wiki-exporter.jenkins.io/progress

### PR DESCRIPTION
**Pull request by zbynek**
Fix sorting, add pull request links and use stats from previous month.

fixes #26

### CODE REVIEW

File: reports.js [hunk 1]
```diff
@@ -57,6 +58,18 @@ async function getContent(url, type) {
...
 }
 
+/**
+ * @return {string} last month date as yyyymm
+ */
+function lastReportDate() {
+  const reportDate = new Date();
+  // needs a bit more than a month https://github.com/jenkins-infra/infra-statistics/blob/master/Jenkinsfile#L18
+  reportDate.setDate(reportDate.getDate() - 35);
+  const month = reportDate.getMonth() + 1; // January: 0 -> 1
```
Comment (halkeye) [inline reports.js]: I suspect this is fixed width, so you probably want to pad it with 0
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

Comment (halkeye) [reply reports.js]: oh you did it with prefix, i see below
